"""Add training_runs table and reviewer_name field

Revision ID: 5eed963bbc03
Revises: 20260323_0001
Create Date: 2026-03-24 00:26:36.881194

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5eed963bbc03"
down_revision = "20260323_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("training_samples", sa.Integer(), nullable=False),
        sa.Column("test_accuracy", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("test_f1", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("test_precision", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("test_recall", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("output_path", sa.String(length=512), nullable=False),
        sa.Column(
            "trained_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "review_annotations", sa.Column("reviewer_name", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_annotations", "reviewer_name")
    op.drop_table("training_runs")
    # ### end Alembic commands ###
